//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum LidarTypeID {
  TYPE_TOF = 0,
  TYPE_TRIANGLE = 1,
  TYPE_TOF_NET = 2,
  TYPE_GS = 3,
  TYPE_SCL = 4,
  TYPE_SDM = 5,
  TYPE_Tail
}
