//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserScan : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserScan(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserScan obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserScan obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserScan() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ydlidarPINVOKE.delete_LaserScan(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ulong stamp {
    set {
      ydlidarPINVOKE.LaserScan_stamp_set(swigCPtr, value);
    } 
    get {
      ulong ret = ydlidarPINVOKE.LaserScan_stamp_get(swigCPtr);
      return ret;
    } 
  }

  public float scanFreq {
    set {
      ydlidarPINVOKE.LaserScan_scanFreq_set(swigCPtr, value);
    } 
    get {
      float ret = ydlidarPINVOKE.LaserScan_scanFreq_get(swigCPtr);
      return ret;
    } 
  }

  public float sampleRate {
    set {
      ydlidarPINVOKE.LaserScan_sampleRate_set(swigCPtr, value);
    } 
    get {
      float ret = ydlidarPINVOKE.LaserScan_sampleRate_get(swigCPtr);
      return ret;
    } 
  }

  public LaserPointVector points {
    set {
      ydlidarPINVOKE.LaserScan_points_set(swigCPtr, LaserPointVector.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ydlidarPINVOKE.LaserScan_points_get(swigCPtr);
      LaserPointVector ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaserPointVector(cPtr, false);
      return ret;
    } 
  }

  public LaserConfig config {
    set {
      ydlidarPINVOKE.LaserScan_config_set(swigCPtr, LaserConfig.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = ydlidarPINVOKE.LaserScan_config_get(swigCPtr);
      LaserConfig ret = (cPtr == global::System.IntPtr.Zero) ? null : new LaserConfig(cPtr, false);
      return ret;
    } 
  }

  public int moduleNum {
    set {
      ydlidarPINVOKE.LaserScan_moduleNum_set(swigCPtr, value);
    } 
    get {
      int ret = ydlidarPINVOKE.LaserScan_moduleNum_get(swigCPtr);
      return ret;
    } 
  }

  public ushort envFlag {
    set {
      ydlidarPINVOKE.LaserScan_envFlag_set(swigCPtr, value);
    } 
    get {
      ushort ret = ydlidarPINVOKE.LaserScan_envFlag_get(swigCPtr);
      return ret;
    } 
  }

  public LaserScan() : this(ydlidarPINVOKE.new_LaserScan(), true) {
  }

}
