//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LaserDebug : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LaserDebug(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LaserDebug obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(LaserDebug obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~LaserDebug() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ydlidarPINVOKE.delete_LaserDebug(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public byte cVer {
    set {
      ydlidarPINVOKE.LaserDebug_cVer_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_cVer_get(swigCPtr);
      return ret;
    } 
  }

  public byte debug2 {
    set {
      ydlidarPINVOKE.LaserDebug_debug2_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_debug2_get(swigCPtr);
      return ret;
    } 
  }

  public byte hfVer {
    set {
      ydlidarPINVOKE.LaserDebug_hfVer_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_hfVer_get(swigCPtr);
      return ret;
    } 
  }

  public byte fVer {
    set {
      ydlidarPINVOKE.LaserDebug_fVer_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_fVer_get(swigCPtr);
      return ret;
    } 
  }

  public byte month {
    set {
      ydlidarPINVOKE.LaserDebug_month_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_month_get(swigCPtr);
      return ret;
    } 
  }

  public byte day {
    set {
      ydlidarPINVOKE.LaserDebug_day_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_day_get(swigCPtr);
      return ret;
    } 
  }

  public byte year {
    set {
      ydlidarPINVOKE.LaserDebug_year_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_year_get(swigCPtr);
      return ret;
    } 
  }

  public byte numH {
    set {
      ydlidarPINVOKE.LaserDebug_numH_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_numH_get(swigCPtr);
      return ret;
    } 
  }

  public byte numL {
    set {
      ydlidarPINVOKE.LaserDebug_numL_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_numL_get(swigCPtr);
      return ret;
    } 
  }

  public byte health {
    set {
      ydlidarPINVOKE.LaserDebug_health_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_health_get(swigCPtr);
      return ret;
    } 
  }

  public byte maxIndex {
    set {
      ydlidarPINVOKE.LaserDebug_maxIndex_set(swigCPtr, value);
    } 
    get {
      byte ret = ydlidarPINVOKE.LaserDebug_maxIndex_get(swigCPtr);
      return ret;
    } 
  }

  public LaserDebug() : this(ydlidarPINVOKE.new_LaserDebug(), true) {
  }

}
