//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum LidarProperty {
  LidarPropSerialPort = 0,
  LidarPropIgnoreArray,
  LidarPropSerialBaudrate = 10,
  LidarPropLidarType,
  LidarPropDeviceType,
  LidarPropSampleRate,
  LidarPropAbnormalCheckCount,
  LidarPropIntenstiyBit,
  LidarPropMaxRange = 20,
  LidarPropMinRange,
  LidarPropMaxAngle,
  LidarPropMinAngle,
  LidarPropScanFrequency,
  LidarPropFixedResolution = 30,
  LidarPropReversion,
  LidarPropInverted,
  LidarPropAutoReconnect,
  LidarPropSingleChannel,
  LidarPropIntenstiy,
  LidarPropSupportMotorDtrCtrl,
  LidarPropSupportHeartBeat
}
